import { expect, it } from 'vitest'
import { dashboardV2Href, parseDashboardRoute } from './routes'

it('parses V2-owned command-center routes', () => {
  expect(parseDashboardRoute('#project:project-1')).toEqual({ page: 'detail', kind: 'project', id: 'project-1', hash: '#project:project-1' })
  expect(parseDashboardRoute('#run:run%2F1')).toEqual({ page: 'detail', kind: 'run', id: 'run/1', hash: '#run:run%2F1' })
  expect(parseDashboardRoute('#paper:paper-1')).toEqual({ page: 'detail', kind: 'paper', id: 'paper-1', hash: '#paper:paper-1' })
  expect(parseDashboardRoute('#event:7')).toEqual({ page: 'detail', kind: 'event', id: '7', hash: '#event:7' })
  expect(parseDashboardRoute('#projects?status=testing')).toEqual({ page: 'projects', status: 'testing', hash: '#projects?status=testing' })
  expect(parseDashboardRoute('#queue:queued')).toEqual({ page: 'queue', status: 'queued', hash: '#queue:queued' })
  expect(parseDashboardRoute('#runs:running')).toEqual({ page: 'runs', state: 'running', hash: '#runs:running' })
  expect(parseDashboardRoute('#runs?state=awaiting_wake')).toEqual({ page: 'runs', state: 'awaiting_wake', hash: '#runs?state=awaiting_wake' })
  expect(parseDashboardRoute('#papers?status=publication_draft')).toEqual({ page: 'papers', status: 'publication_draft', hash: '#papers?status=publication_draft' })
  expect(parseDashboardRoute('#events')).toEqual({ page: 'events', eventType: '', search: '', hash: '#events' })
  expect(parseDashboardRoute('#events?event_type=Queue%20Alert&search=active-lane')).toEqual({ page: 'events', eventType: 'Queue Alert', search: 'active-lane', hash: '#events?event_type=Queue%20Alert&search=active-lane' })
  expect(parseDashboardRoute('#observability')).toEqual({ page: 'observability', hash: '#observability' })
  expect(parseDashboardRoute('#corpus')).toEqual({ page: 'corpus', hash: '#corpus' })
  expect(parseDashboardRoute('#research')).toEqual({ page: 'research', candidateId: '', hash: '#research' })
  expect(parseDashboardRoute('#candidate:cand%2F1')).toEqual({ page: 'research', candidateId: 'cand/1', hash: '#candidate:cand%2F1' })
  expect(parseDashboardRoute('#research:cand%2F1')).toEqual({ page: 'research', candidateId: 'cand/1', hash: '#research:cand%2F1' })
  expect(parseDashboardRoute('#intake')).toEqual({ page: 'intake', ideaId: '', hash: '#intake' })
  expect(parseDashboardRoute('#idea:idea%2F1')).toEqual({ page: 'intake', ideaId: 'idea/1', hash: '#idea:idea%2F1' })
  expect(parseDashboardRoute('#intake:idea%2F1')).toEqual({ page: 'intake', ideaId: 'idea/1', hash: '#intake:idea%2F1' })
  expect(parseDashboardRoute('#automation')).toEqual({ page: 'automation', paperId: '', hash: '#automation' })
  expect(parseDashboardRoute('#automation:paper%2F1')).toEqual({ page: 'automation', paperId: 'paper/1', hash: '#automation:paper%2F1' })
  expect(parseDashboardRoute('#reviews')).toEqual({ page: 'automation', paperId: '', hash: '#reviews' })
  expect(parseDashboardRoute('#review:paper%2F1')).toEqual({ page: 'automation', paperId: 'paper/1', hash: '#review:paper%2F1' })
})

it('keeps dashboard hashes inside the V2 route surface', () => {
  expect(dashboardV2Href('#project:project-1')).toBe('/control/dashboard-v2#project:project-1')
  expect(dashboardV2Href('#run:run-1')).toBe('/control/dashboard-v2#run:run-1')
  expect(dashboardV2Href('#paper:paper-1')).toBe('/control/dashboard-v2#paper:paper-1')
  expect(dashboardV2Href('#event:7')).toBe('/control/dashboard-v2#event:7')
  expect(dashboardV2Href('#projects')).toBe('/control/dashboard-v2#projects')
  expect(dashboardV2Href('#queue:queued')).toBe('/control/dashboard-v2#queue:queued')
  expect(dashboardV2Href('#runs')).toBe('/control/dashboard-v2#runs')
  expect(dashboardV2Href('#papers?status=publication_draft')).toBe('/control/dashboard-v2#papers?status=publication_draft')
  expect(dashboardV2Href('#research')).toBe('/control/dashboard-v2#research')
  expect(dashboardV2Href('#candidate:cand-1')).toBe('/control/dashboard-v2#candidate:cand-1')
  expect(dashboardV2Href('#research:cand-1')).toBe('/control/dashboard-v2#research:cand-1')
  expect(dashboardV2Href('#intake')).toBe('/control/dashboard-v2#intake')
  expect(dashboardV2Href('#idea:idea-1')).toBe('/control/dashboard-v2#idea:idea-1')
  expect(dashboardV2Href('#intake:idea-1')).toBe('/control/dashboard-v2#intake:idea-1')
  expect(dashboardV2Href('#automation')).toBe('/control/dashboard-v2#automation')
  expect(dashboardV2Href('#automation:paper-1')).toBe('/control/dashboard-v2#automation:paper-1')
  expect(dashboardV2Href('#reviews')).toBe('/control/dashboard-v2#reviews')
  expect(dashboardV2Href('#review:paper-1')).toBe('/control/dashboard-v2#review:paper-1')
  expect(dashboardV2Href('#observability')).toBe('/control/dashboard-v2#observability')
  expect(dashboardV2Href('#corpus')).toBe('/control/dashboard-v2#corpus')
  expect(parseDashboardRoute('#unknown-workflow')).toEqual({ page: 'unsupported', hash: '#unknown-workflow' })
  expect(dashboardV2Href('#unknown-workflow')).toBe('/control/dashboard-v2#unknown-workflow')
})
