from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any
from urllib import request

from fastapi import HTTPException

from ..config import GateConfig
from .models import PaperRecord


def _resolve_project_dir(config: GateConfig, candidate: dict[str, Any]) -> Path:
    project_dir_text = str(candidate.get("project_dir") or "").strip()
    if not project_dir_text:
        raise HTTPException(status_code=400, detail="candidate lacks project_dir")
    root = config.expanded_project_root.resolve()
    project_dir = Path(project_dir_text).expanduser()
    if not project_dir.is_absolute():
        project_dir = root / project_dir
    project_dir = project_dir.resolve()
    try:
        project_dir.relative_to(root)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="project_dir escapes configured project root") from exc
    return project_dir


def _write_files(project_dir: Path, files: dict[str, str], *, force: bool) -> None:
    for rel_path, content in files.items():
        target = (project_dir / rel_path).resolve()
        try:
            target.relative_to(project_dir)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=f"paper path escapes project dir: {rel_path}") from exc
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and not force:
            continue
        target.write_text(content, encoding="utf-8")


def deterministic_paper_files(candidate: dict[str, Any], paper: PaperRecord, *, provider_note: str = "deterministic_template_v1") -> dict[str, str]:
    title = str(candidate.get("project_name") or paper.project_id).strip()
    return {
        paper.draft_markdown_path: f"# {title}: Evidence-Grounded Technical Report\n\nStatus: draft_review.\n\nGenerated by LangGraph hard-cutover MVP at {paper.generated_at}.\n\n## Review Required\n\nThis {provider_note} draft proves the new control plane can create paper artifacts. Human review and richer claim extraction are still required.\n",
        paper.draft_latex_path: "\\documentclass{article}\n\\title{" + title.replace("_", "\\_") + "}\n\\author{Enoch LangGraph MVP}\n\\begin{document}\n\\maketitle\nMVP draft for human review.\n\\end{document}\n",
        paper.evidence_bundle_path: json.dumps({"source": "langgraph_control_plane_mvp", "project_id": paper.project_id, "run_id": paper.run_id}, indent=2) + "\n",
        paper.claim_ledger_path: json.dumps({"claims": [], "limitations": ["MVP draft; human review required."], "writer_provider": provider_note}, indent=2) + "\n",
        paper.manifest_path: json.dumps({"paper_id": paper.paper_id, "generated_at": paper.generated_at, "writer_provider": provider_note}, indent=2) + "\n",
    }


def _candidate_context(config: GateConfig, candidate: dict[str, Any], paper: PaperRecord) -> str:
    project_dir = _resolve_project_dir(config, candidate)
    snippets: list[str] = []
    seen: set[Path] = set()

    def add_file(rel: str | Path, *, limit: int = 16000) -> None:
        path = (project_dir / rel).resolve()
        try:
            display = path.relative_to(project_dir)
        except ValueError:
            return
        if path in seen or not path.exists() or not path.is_file():
            return
        seen.add(path)
        text = path.read_text(encoding="utf-8", errors="replace")[:limit]
        snippets.append(f"## {display}\n{text}")

    # High-signal project-level evidence. These are copied from the GB10 worker
    # when legacy paper reviews are rewritten on the VM. Do not omit them: the
    # paper writer must not infer “untested” merely because the VM-local
    # publication folder was freshly generated.
    for rel in ("run_notes.md", ".omx/project_decision.json", ".omx/metrics.json", "logs/main_run.log"):
        add_file(rel, limit=24000)

    # Source paper artifacts from the original research run. These usually carry
    # the claim ledger, evidence strength, tested metrics, and allowed/forbidden
    # wording for publication drafts.
    papers_dir = project_dir / "papers"
    if papers_dir.exists():
        preferred_names = {"evidence_bundle.json", "claim_ledger.json", "paper.md", "paper_manifest.json", "README.md"}
        for path in sorted(papers_dir.rglob("*")):
            if path.is_file() and path.name in preferred_names:
                add_file(path.relative_to(project_dir), limit=22000)

    # Compact result summaries and key JSON outputs. Avoid huge trace CSVs/logs,
    # but include summary CSV/JSON files and top-level result JSONs so the model
    # sees actual measured outcomes.
    results_dir = project_dir / "results"
    if results_dir.exists():
        for path in sorted(results_dir.rglob("*")):
            if not path.is_file():
                continue
            name = path.name.lower()
            if name.endswith(".log") or "trace" in name:
                continue
            if name.endswith("summary.csv") or name.endswith("summary.json") or name in {"hot_cold_sim_results.json", "smoke.json", "hotcold_probe.json"} or ("sweep" in name and name.endswith(".json")):
                add_file(path.relative_to(project_dir), limit=18000)

    return "\n\n".join(snippets) or "No local run artifacts were found; write a cautious review-required draft from the queue metadata only."


def _extract_chat_content(response: dict[str, Any]) -> str:
    choices = response.get("choices") if isinstance(response, dict) else None
    if not choices:
        raise ValueError("missing choices in model response")
    first = choices[0]
    message = first.get("message") if isinstance(first, dict) else None
    content = message.get("content") if isinstance(message, dict) else None
    if isinstance(content, str):
        return content.strip()
    if isinstance(content, list):
        parts = []
        for item in content:
            if isinstance(item, dict):
                text = item.get("text") or item.get("content")
                if isinstance(text, str):
                    parts.append(text)
        if parts:
            return "\n".join(parts).strip()
    raise ValueError("missing text content in model response")


def synthetic_glm_markdown(config: GateConfig, candidate: dict[str, Any], paper: PaperRecord) -> tuple[str, dict[str, Any]]:
    api_key = config.paper_writer_api_key or os.environ.get("SYNTHETIC_API_KEY", "")
    if not api_key:
        raise RuntimeError("Synthetic.new API key is not configured")
    title = str(candidate.get("project_name") or paper.project_id).strip()
    prompt = f"""Write a publication-quality technical paper draft in Markdown for this research result.

Requirements:
- Use a precise academic tone without hype.
- Preserve uncertainty and negative/mixed results honestly.
- Include sections: Abstract, Introduction, Method, Results, Limitations, Reproducibility Checklist, Conclusion.
- Do not invent citations, metrics, hardware results, or claims not supported by the context.
- If the context contains run notes, evidence bundles, claim ledgers, benchmark results, or decision JSON, treat those as empirical/prototype evidence and summarize them accurately. Do NOT say no experiments, no implementation, or no empirical results when those artifacts are present.
- Distinguish carefully between toy simulation results, llama.cpp hook-prototype results, CUDA copy calibration, and final production validation.
- Never write TODO, FIXME, placeholder citations, or "citation needed". If external citation details are not present in the context, omit external references rather than inserting placeholders. Prefer a "Referenced artifacts" section that names the local run notes, evidence bundle, claim ledger, metrics, source files, and result files actually present in the context.
- Keep the draft reviewable and evidence-grounded.
- Include a clear AI provenance / no-human-credit note near the top: this draft was AI-generated from automated research artifacts, the operator claims no personal authorship credit for the writing or results beyond releasing the artifact, and readers should treat it as an unreviewed AI-generated research artifact. Do not require a human reviewer in the note.

Project metadata:
{json.dumps(candidate, indent=2, sort_keys=True)}

Paper id: {paper.paper_id}

Local evidence context:
{_candidate_context(config, candidate, paper)}
"""
    payload = {
        "model": config.paper_writer_model,
        "messages": [
            {"role": "system", "content": "You are an expert scientific paper writer and skeptical claim auditor."},
            {"role": "user", "content": prompt},
        ],
        "temperature": config.paper_writer_temperature,
        "max_tokens": config.paper_writer_max_tokens,
    }
    url = config.paper_writer_base_url.rstrip("/") + "/chat/completions"
    req = request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"},
    )
    with request.urlopen(req, timeout=config.paper_writer_timeout_sec) as resp:  # noqa: S310 - configured operator provider URL
        raw = resp.read().decode("utf-8", errors="replace")
    data = json.loads(raw)
    markdown = _extract_chat_content(data)
    return markdown, {"provider": "synthetic.new", "base_url": config.paper_writer_base_url, "model": config.paper_writer_model, "response_id": data.get("id", "")}


def write_paper_artifacts(config: GateConfig, candidate: dict[str, Any], paper: PaperRecord, *, force: bool) -> dict[str, Any]:
    project_dir = _resolve_project_dir(config, candidate)
    provider = config.paper_writer_provider.strip().lower()
    files = deterministic_paper_files(candidate, paper)
    meta: dict[str, Any] = {"provider": "deterministic", "model": "deterministic_template_v1", "fallback_used": False}
    if provider in {"synthetic", "synthetic.new", "synthetic_glm"}:
        try:
            markdown, provider_meta = synthetic_glm_markdown(config, candidate, paper)
            files = deterministic_paper_files(candidate, paper, provider_note="synthetic.new/glm-5.1")
            files[paper.draft_markdown_path] = markdown + "\n"
            files[paper.manifest_path] = json.dumps({"paper_id": paper.paper_id, "generated_at": paper.generated_at, "writer_provider": provider_meta}, indent=2, sort_keys=True) + "\n"
            files[paper.claim_ledger_path] = json.dumps({"claims": [], "limitations": ["Model-authored draft; human claim audit required."], "writer_provider": provider_meta}, indent=2, sort_keys=True) + "\n"
            evidence_target = (project_dir / paper.evidence_bundle_path).resolve()
            try:
                evidence_target.relative_to(project_dir)
            except ValueError as exc:
                raise HTTPException(status_code=400, detail=f"paper path escapes project dir: {paper.evidence_bundle_path}") from exc
            if evidence_target.exists() and evidence_target.is_file():
                # Preserve imported research evidence. The generated publication
                # draft must not replace a real evidence bundle with an MVP
                # writer marker, or later rewrites will incorrectly conclude the
                # project was untested.
                files.pop(paper.evidence_bundle_path, None)
            meta = {**provider_meta, "fallback_used": False}
        except Exception as exc:
            if not config.paper_writer_fallback_enabled:
                raise HTTPException(status_code=502, detail=f"paper writer provider failed: {type(exc).__name__}: {exc}") from exc
            meta = {"provider": "deterministic", "model": "deterministic_template_v1", "fallback_used": True, "fallback_reason": f"{type(exc).__name__}: {exc}", "requested_provider": provider}
            files = deterministic_paper_files(candidate, paper, provider_note="deterministic fallback after Synthetic.new/GLM-5.1 failure")
    elif provider not in {"deterministic", "template"}:
        raise HTTPException(status_code=400, detail=f"unsupported paper_writer_provider: {config.paper_writer_provider}")
    _write_files(project_dir, files, force=force)
    return meta
